"use client";

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import ContentRenderer from './content-renderer';
import type { GenerateSimilarQuestionOutput } from '@/ai/flows/generate-similar-question';

interface QuestionDisplayProps {
  question: GenerateSimilarQuestionOutput;
}

export default function QuestionDisplay({ question }: QuestionDisplayProps) {
  return (
    <Card className="border-primary/50 shadow-lg">
      <CardHeader>
        <CardTitle>Generated Question</CardTitle>
        <CardDescription>
          This question was generated by AI based on the base question.
        </CardDescription>
        <div className="flex flex-wrap gap-2 pt-2">
            <Badge variant="secondary">{question.subject}</Badge>
            <Badge variant="secondary">{question.unit}</Badge>
            <Badge variant="secondary">{question.topic}</Badge>
        </div>
      </CardHeader>
      <CardContent>
        <ContentRenderer content={question.newQuestionText} />
      </CardContent>
    </Card>
  );
}
