"use client";

import { useState } from 'react';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { useToast } from '@/hooks/use-toast';
import { generateQuestionAction } from '@/app/actions';
import ContentRenderer from './content-renderer';
import { Loader2, Copy } from 'lucide-react';
import { Skeleton } from './ui/skeleton';
import type { GenerateSimilarQuestionOutput } from '@/ai/flows/generate-similar-question';
import { Textarea } from './ui/textarea';


interface QuestionGeneratorProps {
  baseQuestion: {
    id: string;
    text: string;
  };
}

const LoadingSkeleton = () => (
    <Card className="mt-6">
        <CardHeader>
            <Skeleton className="h-6 w-1/2" />
        </CardHeader>
        <CardContent className="space-y-4">
            <Skeleton className="h-40 w-full" />
        </CardContent>
    </Card>
);

export default function QuestionGenerator({ baseQuestion }: QuestionGeneratorProps) {
  const [isLoading, setIsLoading] = useState(false);
  const [generatedQuestion, setGeneratedQuestion] = useState<string | null>(null);
  const { toast } = useToast();

  const handleGenerate = async () => {
    setIsLoading(true);
    setGeneratedQuestion(null);
    try {
      const result = await generateQuestionAction(baseQuestion.text);
      if ('error' in result) {
        toast({
          variant: 'destructive',
          title: 'Error generating question',
          description: result.error,
        });
      } else {
        setGeneratedQuestion(result.generatedQuestion);
      }
    } catch (error) {
      toast({
        variant: 'destructive',
        title: 'An unexpected error occurred',
        description: 'Please try again later.',
      });
    } finally {
      setIsLoading(false);
    }
  };

  const handleCopy = () => {
    if (generatedQuestion) {
      navigator.clipboard.writeText(generatedQuestion);
      toast({
        title: 'Copied to clipboard!',
        description: 'The generated question has been copied.',
      });
    }
  };

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>Base Question</CardTitle>
          <CardDescription>This is the question used as a base for generation.</CardDescription>
        </CardHeader>
        <CardContent>
          <ContentRenderer content={baseQuestion.text} />
        </CardContent>
        <CardFooter>
          <Button onClick={handleGenerate} disabled={isLoading} className="w-full sm:w-auto">
            {isLoading ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Generating...
              </>
            ) : (
              'Generate Similar Question'
            )}
          </Button>
        </CardFooter>
      </Card>

      {isLoading && <LoadingSkeleton />}
      
      {generatedQuestion && (
        <Card className="fade-in">
          <CardHeader>
            <div className="flex justify-between items-center">
                <CardTitle>Generated Question</CardTitle>
                <Button variant="ghost" size="icon" onClick={handleCopy}>
                    <Copy className="h-5 w-5" />
                </Button>
            </div>
            <CardDescription>This question was generated by AI based on the base question.</CardDescription>
          </CardHeader>
          <CardContent>
            <Textarea
              readOnly
              value={generatedQuestion}
              className="h-96 text-sm font-mono"
            />
          </CardContent>
        </Card>
      )}
    </div>
  );
}
