"use client";

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { useToast } from '@/hooks/use-toast';
import { Copy } from 'lucide-react';
import type { GenerateSimilarQuestionOutput } from '@/ai/flows/generate-similar-question';

interface QuestionDisplayProps {
  question: GenerateSimilarQuestionOutput;
}

export default function QuestionDisplay({ question }: QuestionDisplayProps) {
  const { toast } = useToast();

  const handleCopy = () => {
    navigator.clipboard.writeText(question.question);
    toast({
      title: 'Copied to clipboard!',
      description: 'The generated question has been copied.',
    });
  };

  return (
    <Card className="border-primary/50 shadow-lg">
      <CardHeader>
        <div className="flex justify-between items-start">
            <div>
                <CardTitle>Generated Question</CardTitle>
                <CardDescription>
                This question was generated by AI based on the base question.
                </CardDescription>
            </div>
            <Button variant="ghost" size="icon" onClick={handleCopy} aria-label="Copy to clipboard">
                <Copy className="h-5 w-5" />
            </Button>
        </div>
      </CardHeader>
      <CardContent>
        <Textarea
          readOnly
          value={question.question}
          className="h-96 w-full font-mono text-sm"
          aria-label="Generated Question"
        />
      </CardContent>
    </Card>
  );
}
